name: CI

on:
  push:
  release:
    types: [created]
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: set up dotnet core 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: publish
      run: dotnet publish -c Release /p:Platform="Any CPU" --framework=net6.0 -o ur_robotraconteur_driver
    - name: copy license and readme
      run: |
        Copy-Item -Path LICENSE.txt -Destination ur_robotraconteur_driver
        Copy-Item -Path README.md -Destination ur_robotraconteur_driver
    - name: zip
      run: Compress-Archive -Path ur_robotraconteur_driver -DestinationPath ur_robotraconteur_driver.zip
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: ur_robotraconteur_driver
        path: ur_robotraconteur_driver.zip
  pre-commit:
    runs-on: ubuntu-22.04
    env:
      SKIP: no-commit-to-branch
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
    - name: apt
      run: |
        sudo apt update
        sudo apt install -y dos2unix
    - name: Setup dotnet 6.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
    - uses: pre-commit/action@v3.0.1
